# Generated by Django 3.1 on 2022-02-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
